### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by ghost** [superischroma/Spectaculation#1]
Hey! No problem with the project, just could not find another way to contact you. Is it true skysim did something with this? or is it just some rumor? Any ways nice plugin man <3

**Comment by meowaphina** [comment]
Firstly Eman, Skysim was based of it but it has changed a lot and we know your goal is to take it, and no this one contains many issues the author has just recently deleted the repo, You cannot just use this it doesn't work in multiplayer, the plugin is a mess and would need a lot of fixing skysim has fully moved away from this and no longer uses this as a base, you cannot fool me, I see a lot EMAN you cant just do this, I'm not dumb, if you think you can get away from doing this, no you cannot yes it is some rumor if you use this plugin you are exposing yourself because I know you use visual bukkit and cannot code java, so you would never be able to recode this plugin, visual bukkit is an embarrassment you have proven to everyone that you cannot code java
the more you lie the worse this will get no one will join your server, because it is just broken doesn't work uses 98% public plugins you claim that you coded blockregenx no you did not I have exposed you in the past, you used visual bukkit, you has also tried to hide it by only sending the main class but there is something called java decompiler I saw the visual bukkit files, visual bukkit is for lazy people and idiots, DO you WANT to be exposed more, you used an anvil to make ur juju bow you use public plugins to create items, you use MULTIPLE plugins which are spottable from a mile away, you need to stop doing this this will progressively get worse and no not nice plugin, the fact that you are going to attempt to steal this project even tho you do not even know how to build the project I believe you have spent all these 12 hours trying to figure out why it wont build I will not let this slide you have exposed YOURSELF not me YOU DID IT TO URSELF so please can you stop calling yourself a java developer CHANGE YOUR STATUS I cannot believe you a lier, a idiot, a faker, and a just overall pain CAN YOU STOP PUTTING YOURSELF ON THE INTERNET you will GET harrassed by many people THIS IS NOT ok anymore I AM saying THIS HERE IS THE BOUNDRY MOVE PAST AND YOU WONT COME BACK, GOOD BYE!

**Comment by meowaphina** [comment]
> Hey! No problem with the project, just could not find another way to contact you. Is it true skysim did something with this? or is it just some rumor? Any ways nice plugin man <3

^

**Comment by ghost** [comment]
> Firstly Eman, Skysim was based of it but it has changed a lot and we know your goal is to take it, and no this one contains many issues the author has just recently deleted the repo, You cannot just use this it doesn't work in multiplayer, the plugin is a mess and would need a lot of fixing skysim has fully moved away from this and no longer uses this as a base, you cannot fool me, I see a lot EMAN you cant just do this, I'm not dumb, if you think you can get away from doing this, no you cannot yes it is some rumor if you use this plugin you are exposing yourself because I know you use visual bukkit and cannot code java, so you would never be able to recode this plugin, visual bukkit is an embarrassment you have proven to everyone that you cannot code java the more you lie the worse this will get no one will join your server, because it is just broken doesn't work uses 98% public plugins you claim that you coded blockregenx no you did not I have exposed you in the past, you used visual bukkit, you has also tried to hide it by only sending the main class but there is something called java decompiler I saw the visual bukkit files, visual bukkit is for lazy people and idiots, DO you WANT to be exposed more, you used an anvil to make ur juju bow you use public plugins to create items, you use MULTIPLE plugins which are spottable from a mile away, you need to stop doing this this will progressively get worse and no not nice plugin, the fact that you are going to attempt to steal this project even tho you do not even know how to build the project I believe you have spent all these 12 hours trying to figure out why it wont build I will not let this slide you have exposed YOURSELF not me YOU DID IT TO URSELF so please can you stop calling yourself a java developer CHANGE YOUR STATUS I cannot believe you a lier, a idiot, a faker, and a just overall pain CAN YOU STOP PUTTING YOURSELF ON THE INTERNET you will GET harrassed by many people THIS IS NOT ok anymore I AM saying THIS HERE IS THE BOUNDRY MOVE PAST AND YOU WONT COME BACK, GOOD BYE

Hey, I was not asking you

**Comment by ghost** [comment]
> 

2 Things also 

1: I am not a java develpoer, I use C++
2: I did use java here is some work of mine

package me.Eman.Ecore;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

public class Main extends JavaPlugin{
	
	public boolean onCommand(CommandSender commandSender, Command command, String label, String[] commandArgs) {
		if (command.getName().equalsIgnoreCase("help")) {
			try {
				Object localVariableScope = new Object();
				commandSender.sendMessage(Color.color("&eGo to &7&owwww.youtube.com/eman49&e,"));
				commandSender.sendMessage(Color.color("&eor do &9&l/discord &efor help!"));
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		
		return true;
	}

	
	
	
	@Override
	public void onEnable() {
	    System.out.println("Plugin Has been Enabled!");
	}
	
	
	
	@Override
	public void onDisable() {
	    System.out.println("Plugin Has been Disabled!");
	}
	
}


(Not the cleaniest but it works)

also the Color.color is from a class called color ()

Thanks for reading and have a nice day, also leave me alone
